name: Release npm package to npmjs

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: publish npmjs
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    # no test now...
    # - run: npm install
    # - run: npm run build --if-present
    # - run: npm test
    #   env:
    #     CI: true